version: '3.9'

#Useful commands
#docker exec docker_zookeeper-1_1 bash -c 'echo mntr | nc localhost 2181'
#docker exec docker_zookeeper-1_1 bash -c 'echo srvr | nc localhost 2181'
#docker-compose -f docker-compose-kafka-cluster.yml rm -svf
#kafkacat -L -b localhost

x-zookeeper: &zookeeper
  image: confluentinc/cp-zookeeper:6.1.0
  restart: always
  networks:
    - zookeeper
  tmpfs:
    - /var/lib/zookeeper/log
    - /var/lib/zookeeper/data

x-zookeeper-environment: &zookeeper-environment
  ZOOKEEPER_CLIENT_PORT: 2181
  ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
  ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: ERROR
  KAFKA_HEAP_OPTS: "-Xmx128m -Xms64m"
  KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"

x-kafka: &kafka
  image: confluentinc/cp-kafka:6.1.0
  restart: always
  networks:
    - zookeeper
    - kafka
  tmpfs:
    - /var/lib/kafka/data

x-kafka-environment: &kafka-environment
  KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
  KAFKA_HEAP_OPTS: "-Xmx512m -Xms128m"
  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
  KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
  KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
  KAFKA_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.apache.kafka=ERROR,kafka=ERROR,kafka.cluster=ERROR,kafka.controller=ERROR,kafka.coordinator=ERROR,kafka.log=ERROR,kafka.server=ERROR,kafka.zookeeper=ERROR,state.change.logger=ERROR,kafka.log.LogCleaner=ERROR

services:
  zookeeper-1:
    <<: *zookeeper
    environment:
      <<: *zookeeper-environment
      ZOOKEEPER_SERVER_ID: 1
  zookeeper-2:
    <<: *zookeeper
    environment:
      <<: *zookeeper-environment
      ZOOKEEPER_SERVER_ID: 2
  zookeeper-3:
    <<: *zookeeper
    environment:
      <<: *zookeeper-environment
      ZOOKEEPER_SERVER_ID: 3
  kafka-1:
    <<: *kafka
    ports:
      - 9092:9092
    environment:
      <<: *kafka-environment
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INTERNAL://:9090,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9090,EXTERNAL://localhost:9092
  kafka-2:
    <<: *kafka
    ports:
      - 19092:19092
    environment:
      <<: *kafka-environment
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: INTERNAL://:9090,EXTERNAL://:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9090,EXTERNAL://localhost:19092
  kafka-3:
    <<: *kafka
    ports:
      - 29092:29092
    environment:
      <<: *kafka-environment
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: INTERNAL://:9090,EXTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9090,EXTERNAL://localhost:29092

networks:
  zookeeper:
  kafka:
